/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pim.contact;

import java.awt.image.BufferedImage;
import java.util.Properties;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import pim.*;

/**
 *
 * @author lk
 */
public class CreateContactDialog extends javax.swing.JDialog {

    private Contact contact;
    private BufferedImage image;
    
    /**
     * Creates new form CreateContactPanel
     */
    public CreateContactDialog(java.awt.Frame parent, boolean modal, Contact contact) {
        super(parent, modal);
        this.contact = contact;
        initComponents();
        setTexts(Settings.locale);
        
        TextFieldListener textFieldListener = new TextFieldListener();
        jTextFieldName.addMouseListener(textFieldListener);
        jTextFieldMail.addMouseListener(textFieldListener);
        jTextFieldMobil.addMouseListener(textFieldListener);
        jTextFieldDescription1.addMouseListener(textFieldListener);
        jTextFieldDescription2.addMouseListener(textFieldListener);
        jTextFieldDescription3.addMouseListener(textFieldListener);
        jTextFieldContent1.addMouseListener(textFieldListener);
        jTextFieldContent2.addMouseListener(textFieldListener);
        jTextFieldContent3.addMouseListener(textFieldListener);
        
        if (contact != null) {
            jTextFieldName.setText(contact.getName());
            jTextFieldMail.setText(contact.getMail());
            jTextFieldMobil.setText(contact.getNumber());
            jTextFieldDescription1.setText(contact.getDescription1());
            jTextFieldContent1.setText(contact.getContent1());
            jTextFieldDescription2.setText(contact.getDescription2());
            jTextFieldContent2.setText(contact.getContent2());
            jTextFieldDescription3.setText(contact.getDescription3());
            jTextFieldContent3.setText(contact.getContent3());
            image = contact.getImage();
            if (image != null) {
                jLabelImage.setIcon(new ImageIcon(image));
            }
            jTextFieldName.setCaretPosition(0);
            jTextFieldMail.setCaretPosition(0);
            jTextFieldMobil.setCaretPosition(0);
            jTextFieldDescription1.setCaretPosition(0);
            jTextFieldContent1.setCaretPosition(0);
            jTextFieldDescription2.setCaretPosition(0);
            jTextFieldContent2.setCaretPosition(0);
            jTextFieldDescription3.setCaretPosition(0);
            jTextFieldContent3.setCaretPosition(0);
        }
    }

     public void setTexts(String locale) {
        Properties texts = null;
        switch (locale) {
            case "en":
                texts = Texts.props_en;
                break;
            case "de":
                texts = Texts.props_de;
                break;
        }

        if (texts != null) {
            
            jLabelName.setText(texts.getProperty("jLabelContactName") + ":");
            jLabelMail.setText(texts.getProperty("jLabelContactMail") + ":");
            jLabelNumber.setText(texts.getProperty("jLabelContactNumber") + ":");
            jLabelMoreFields.setText(texts.getProperty("jLabelMoreFields"));
            jLabelDescription.setText(texts.getProperty("jLabelDescription"));
            jLabelContent.setText(texts.getProperty("jLabelContent"));
            jButtonOk.setText(texts.getProperty("jButtonContactsOk"));
            jButtonCancel.setText(texts.getProperty("jButtonContactsCancel"));
        }

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();
        jLabelMail = new javax.swing.JLabel();
        jLabelNumber = new javax.swing.JLabel();
        jTextFieldMail = new javax.swing.JTextField();
        jTextFieldMobil = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelMoreFields = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelContent = new javax.swing.JLabel();
        jTextFieldDescription1 = new javax.swing.JTextField();
        jTextFieldDescription2 = new javax.swing.JTextField();
        jTextFieldDescription3 = new javax.swing.JTextField();
        jTextFieldContent1 = new javax.swing.JTextField();
        jTextFieldContent2 = new javax.swing.JTextField();
        jTextFieldContent3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelImage = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelName.setText("Name:");

        jButtonOk.setText("OK");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jLabelMail.setText("E-Mail:");

        jLabelNumber.setText("Nummer:");

        jButtonCancel.setText("Abbrechen");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelMoreFields.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMoreFields.setText("Weitere Felder");

        jLabelDescription.setText("Bezeichnung");

        jLabelContent.setText("Inhalt");

        jTextFieldContent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContent2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelMoreFields)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldDescription3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDescription2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDescription1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelContent)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldContent1)
                    .addComponent(jTextFieldContent2)
                    .addComponent(jTextFieldContent3)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelMoreFields)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescription)
                    .addComponent(jLabelContent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescription3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pim/icons/member.png"))); // NOI18N
        jLabelImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelImage.setOpaque(true);
        jLabelImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelMail)
                            .addComponent(jLabelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldMail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(jTextFieldMobil, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelImage)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMail)
                    .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumber)
                    .addComponent(jTextFieldMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImage)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        String name = jTextFieldName.getText().trim();
        if (!name.isEmpty()) {
            String mail = jTextFieldMail.getText().trim();
            String number = jTextFieldMobil.getText().trim();
            String description1 = jTextFieldDescription1.getText().trim();
            String content1 = jTextFieldContent1.getText().trim();
            String description2 = jTextFieldDescription2.getText().trim();
            String content2 = jTextFieldContent2.getText().trim();
            String description3 = jTextFieldDescription3.getText().trim();
            String content3 = jTextFieldContent3.getText().trim();
            
            boolean test = true;
            if (!description1.isEmpty() && content1.isEmpty()) {
                jTextFieldContent1.requestFocus();
                test = false;
            }
            if (description1.isEmpty() && !content1.isEmpty()) {
                jTextFieldDescription1.requestFocus();
                test = false;
            }
            if (!description2.isEmpty() && content2.isEmpty()) {
                jTextFieldContent2.requestFocus();
                test = false;
            }
            if (description2.isEmpty() && !content2.isEmpty()) {
                jTextFieldDescription2.requestFocus();
                test = false;
            }
            if (!description3.isEmpty() && content3.isEmpty()) {
                jTextFieldContent3.requestFocus();
                test = false;
            }
            if (description3.isEmpty() && !content3.isEmpty()) {
                jTextFieldDescription3.requestFocus();
                test = false;
            }
            
            if (test) {
                if (contact == null) {
                    contact = new Contact(name, mail, number, description1, content1,
                            description2, content2, description3, content3, image);
                } else {
                    contact.setName(name);
                    contact.setMail(mail);
                    contact.setNumber(number);
                    contact.setDescription1(description1);
                    contact.setContent1(content1);
                    contact.setDescription2(description2);
                    contact.setContent2(content2);
                    contact.setDescription3(description3);
                    contact.setContent3(content3);
                    contact.setImage(image);
                }
                this.dispose();
            }
        } else {
            jTextFieldName.setText("");
            jTextFieldName.requestFocus();
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        contact = null;
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jLabelImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImageMouseClicked
        image = ImageChooser.chooseImage();
        if (image != null) {
            jLabelImage.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_jLabelImageMouseClicked

    private void jTextFieldContent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContent2ActionPerformed
    
    public Contact getContact() {
        return contact;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelContent;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelMoreFields;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldContent1;
    private javax.swing.JTextField jTextFieldContent2;
    private javax.swing.JTextField jTextFieldContent3;
    private javax.swing.JTextField jTextFieldDescription1;
    private javax.swing.JTextField jTextFieldDescription2;
    private javax.swing.JTextField jTextFieldDescription3;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldMobil;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
