/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pim.notes;

import java.awt.Color;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Beware
 */
public class NoteItem extends javax.swing.JPanel implements Comparable<NoteItem>{

    private final Color BACK_COLOR = new Color(236, 227, 159);
    private final Color SELECT_COLOR = new Color(244, 239, 202);
    private final SimpleDateFormat SDF = new SimpleDateFormat("dd.MM.yyyy   HH:mm");
    
    private int pos;
    private Note note;
    private String title;
    private Date date;
    private String content;
    
    /**
     * Creates new form NoteItem
     */
    public NoteItem(Note note) {
        
        initComponents();
        jTextAreaContent.setBorder(null);
        jTextAreaContent.setLineWrap(true);
        jTextAreaContent.setWrapStyleWord(true);

        this.note = note;
        pos = 0;
        title = note.getTitle();
        date = note.getCreateDate();
        content = note.getNoteContent();
        
        jLabelTitle.setText(title);
        jTextAreaContent.setText(content);
        jLableDate.setText(SDF.format(getDate()));
       
    }
    
    public Note getNote() {
        return note;
    }

    public void setNote(Note note) {
        this.note = note;
        setTitle(note.getTitle());
        setDate(note.getCreateDate());
        setContent(note.getNoteContent());
        jLabelTitle.setText(getTitle());
        jTextAreaContent.setText(getContent());
        jLableDate.setText(SDF.format(getDate()));
    }
    
    public int getPosition() {
        return pos;
    }
    
    public void setPosition(int pos) {
        this.pos = pos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLableDate = new javax.swing.JLabel();
        jScrollPaneContent = new javax.swing.JScrollPane();
        jTextAreaContent = new javax.swing.JTextArea();
        jLabelTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 227, 159));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(270, 155));

        jLableDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLableDate.setText("Datum");

        jScrollPaneContent.setBorder(null);

        jTextAreaContent.setEditable(false);
        jTextAreaContent.setBackground(new java.awt.Color(236, 227, 159));
        jTextAreaContent.setLineWrap(true);
        jTextAreaContent.setText("...");
        jTextAreaContent.setBorder(null);
        jTextAreaContent.setFocusable(false);
        jScrollPaneContent.setViewportView(jTextAreaContent);

        jLabelTitle.setBackground(new java.awt.Color(120, 68, 41));
        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Title");
        jLabelTitle.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLableDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPaneContent)
                .addGap(6, 6, 6))
            .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitle)
                .addGap(6, 6, 6)
                .addComponent(jScrollPaneContent, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLableDate))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLableDate;
    private javax.swing.JScrollPane jScrollPaneContent;
    private javax.swing.JTextArea jTextAreaContent;
    // End of variables declaration//GEN-END:variables

    //Unused in this programversion
    @Override
    public int compareTo(NoteItem o) {
        if (o.getTitle( ).isEmpty() && this.getTitle().isEmpty()) {
          return 0;
        }
        if (o.getTitle().isEmpty()) {
          return 1;
        }
        if (note.getTitle().isEmpty()) {
          return -1;
        }
        return this.getTitle().compareTo(o.getTitle());
    }

    /**
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    
    /**
     * @param title the title to set
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * @return the date
     */
    public Date getDate() {
        return date;
    }

    /**
     * @param date the date to set
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * @return the content
     */
    public String getContent() {
        return content;
    }

    /**
     * @param content the content to set
     */
    public void setContent(String content) {
        this.content = content;
    }

    
    public void addListener(MouseListener listener) {
        addMouseListener(listener);
        jTextAreaContent.addMouseListener(listener);
    }

    public void select() {
        setBackground(SELECT_COLOR);
        jTextAreaContent.setBackground(SELECT_COLOR);
    }

    public void unselect() {
        setBackground(BACK_COLOR);
        jTextAreaContent.setBackground(BACK_COLOR);
    }
}

