/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pim.exam;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import pim.*;

/**
 *
 * @author lk
 */
public class CreateExamDialog extends javax.swing.JDialog {
    
    private Exam exam;
    private boolean changed;
    
    
    /**
     * Creates new form NewJDialog
     */
    public CreateExamDialog(java.awt.Frame parent, boolean modal, Exam exam) {
        super(parent, modal);
        this.exam = exam;
        changed = false;
        initComponents();
        
        TextFieldListener textFieldListener = new TextFieldListener();
        jTextFieldSubject.addMouseListener(textFieldListener);
        jTextFieldTime.addMouseListener(textFieldListener);
        jTextFieldRoom.addMouseListener(textFieldListener);
        dateChooserCombo.setCurrent(null);
        
        if (exam != null) {
            if (exam.getDate() != null) {
                Calendar c = Calendar.getInstance();
                c.setTime(exam.getDate());
                dateChooserCombo.setSelectedDate(c);
                SimpleDateFormat f = new SimpleDateFormat("HH:mm");  
                jTextFieldTime.setText(f.format(exam.getDate()));
            } else {
                dateChooserCombo.setSelectedDate(null);
            }
            jTextFieldSubject.setText(exam.getSubject());
            jComboBoxSemester.setSelectedItem(exam.getSemester());
            jComboBoxEcts.setSelectedIndex(exam.getEcts() - 1);
            jTextFieldRoom.setText(exam.getRoom());
        }
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSubject = new javax.swing.JLabel();
        jLabelSemester = new javax.swing.JLabel();
        jLabelEcts = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabelRoom = new javax.swing.JLabel();
        jTextFieldRoom = new javax.swing.JTextField();
        jTextFieldTime = new javax.swing.JTextField();
        jComboBoxEcts = new javax.swing.JComboBox();
        jComboBoxSemester = new javax.swing.JComboBox();
        jTextFieldSubject = new javax.swing.JTextField();
        jButtonSubmit = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        dateChooserCombo = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Klausur erstellen");
        setResizable(false);

        jLabelSubject.setText("Fach:");

        jLabelSemester.setText("Semester:");

        jLabelEcts.setText("ECTS:");

        jLabelDate.setText("Datum:");

        jLabelTime.setText("Uhrzeit:");

        jLabelRoom.setText("Raum:");

        jTextFieldRoom.setDocument(new pim.JTextFieldLimit(40));

        jTextFieldTime.setDocument(new pim.JTextFieldLimit(40));

        jComboBoxEcts.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        jTextFieldSubject.setDocument(new pim.JTextFieldLimit(40));

        jButtonSubmit.setText("Eintragen");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Abbrechen");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        dateChooserCombo.setCalendarPreferredSize(new java.awt.Dimension(340, 180));
        dateChooserCombo.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSemester)
                            .addComponent(jLabelSubject)
                            .addComponent(jLabelEcts)
                            .addComponent(jLabelDate)
                            .addComponent(jLabelTime)
                            .addComponent(jLabelRoom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSubject, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxSemester, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxEcts, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTime)
                            .addComponent(jTextFieldRoom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateChooserCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSubject)
                    .addComponent(jTextFieldSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSemester)
                    .addComponent(jComboBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEcts)
                    .addComponent(jComboBoxEcts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRoom)
                    .addComponent(jTextFieldRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonSubmit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBoxSemester.setModel(new javax.swing.DefaultComboBoxModel(Exam.SEMESTER));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private Date getDate() {
        Date date = null;
        Calendar cal = Calendar.getInstance();
        cal.setTime(dateChooserCombo.getCurrent().getTime());
        Pattern pattern = Pattern.compile("(\\d\\d?):(\\d\\d)");
        Matcher matcher = pattern.matcher(jTextFieldTime.getText().trim());
        if (matcher.find()) {
            int hours = Integer.parseInt(matcher.group(1));
            int minutes = Integer.parseInt(matcher.group(2));
            if (hours < 24 && minutes < 60) {
                cal.set(Calendar.HOUR_OF_DAY, hours);
                cal.set(Calendar.MINUTE, minutes);
                date = cal.getTime();
            }
        }
        return date;
    }
    
    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        String subject = jTextFieldSubject.getText().trim();
        
        if (subject.isEmpty()) {
            jTextFieldSubject.setText("");
            jTextFieldSubject.requestFocus();
            return;
        }
        
        if (dateChooserCombo.getSelectedDate() == null && !jTextFieldTime.getText().trim().isEmpty()) {
            dateChooserCombo.requestFocus();
            return;
        }
        
        Date date = null;
        if (dateChooserCombo.getSelectedDate() != null) {
            date = getDate();
            if (date == null) {
                jTextFieldTime.requestFocus();
                jTextFieldTime.setSelectionStart(0);
                jTextFieldTime.setSelectionEnd(jTextFieldTime.getText().length());
                return;
            }
        }
        
        String semester = (String) jComboBoxSemester.getSelectedItem();
        int ects = jComboBoxEcts.getSelectedIndex() + 1;
        String room = jTextFieldRoom.getText().trim();
        if (exam == null) {
            exam = new Exam(subject, semester, ects, date, room, 0d, null);
        } else {
            exam.setSubject(subject);
            exam.setSemester(semester);
            exam.setEcts(ects);
            exam.setDate(date);
            exam.setRoom(room);
        }
        changed = true;
        this.dispose();
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    
    public Exam getExam() {
        if (changed) {
            return exam;
        } else {
            return null;
        }     
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox jComboBoxEcts;
    private javax.swing.JComboBox jComboBoxSemester;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelEcts;
    private javax.swing.JLabel jLabelRoom;
    private javax.swing.JLabel jLabelSemester;
    private javax.swing.JLabel jLabelSubject;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JTextField jTextFieldRoom;
    private javax.swing.JTextField jTextFieldSubject;
    private javax.swing.JTextField jTextFieldTime;
    // End of variables declaration//GEN-END:variables
}
