/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pim;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lk
 */
public class DatabaseSettingsDialog extends javax.swing.JDialog {

    
    private static final String database = "pim";
    
    /**
     * Creates new form DatabaseSettingsDialog
     */
    public DatabaseSettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        TextFieldListener textFieldListener = new TextFieldListener();
        jTextFieldServer.addMouseListener(textFieldListener);
        jTextFieldUser.addMouseListener(textFieldListener);
        jTextFieldPassword.addMouseListener(textFieldListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelServer = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jTextFieldServer = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonTest = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldPassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelServer.setText("Server:");

        jLabelUser.setText("Benutzername:");

        jLabelPassword.setText("Passwort:");

        jTextFieldUser.setText("root");

        jTextFieldServer.setText("localhost");

        jButtonOk.setText("OK");

        jButtonCancel.setText("Abbrechen");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonTest.setText("Teste Verbindung");
        jButtonTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Datenbank löschen");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonTest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonOk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUser)
                            .addComponent(jLabelServer)
                            .addComponent(jLabelPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldUser, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldServer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextFieldPassword))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelServer)
                    .addComponent(jTextFieldServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUser)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTest)
                    .addComponent(jButtonOk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
         this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestActionPerformed
        String connection = "jdbc:mysql://" + jTextFieldServer.getText();
    	String user = jTextFieldUser.getText();
        String password = jTextFieldPassword.getText();
        
        Connection con;
        Statement stmt;
        
        try {
            con = DriverManager.getConnection(connection, user, password);
            stmt = con.createStatement();
            try {
                stmt.execute("USE `" + database + "`");
            } catch (SQLException e) {
                stmt.executeUpdate("CREATE SCHEMA `" + database + "`");
                createNewDatabase(con);
            }
            stmt.execute("USE `" + database + "`");
            con.close();
            JOptionPane.showMessageDialog(this, "Verbindung erfolgreich.");
        } catch (SQLException e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Es konnte keine Verbindung zur Datenbank hergestellt werden.", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonTestActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
         
        Object[] options = {"Ja", "Nein"};
        int n = JOptionPane.showOptionDialog(this,
                "Gesamter Inhalt der Datenbank löschen?",
                "Löschen bestätigen",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);

            if (n == 0) {
                String connection = "jdbc:mysql://" + jTextFieldServer.getText();
                String user = jTextFieldUser.getText();
                String password = jTextFieldPassword.getText();

                Connection con;

                try {
                    con = DriverManager.getConnection(connection, user, password);
                    createNewDatabase(con);
                    con.close();
                } catch (SQLException e) {
                    System.err.println(e.getMessage());
                    JOptionPane.showMessageDialog(this, "Es konnte keine Verbindung zur Datenbank hergestellt werden.", "Fehler", JOptionPane.ERROR_MESSAGE);
                }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed
    
    
    private void createNewDatabase(Connection con) throws SQLException {
        try (Statement stmt = con.createStatement()) {
            stmt.execute("DROP SCHEMA IF EXISTS `" + database + "");
            stmt.executeUpdate("CREATE SCHEMA `" + database + "`");

            stmt.executeUpdate("CREATE TABLE  `pim`.`exams` ( "
                    + "`subject` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '', "
                    + "`semester` tinyint(3) unsigned NOT NULL DEFAULT '0', "
                    + "`ects` tinyint(3) unsigned NOT NULL DEFAULT '0', "
                    + "`date` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '', "
                    + "`time` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '', "
                    + "`room` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '', "
                    + "`grade` float unsigned NOT NULL DEFAULT '0', "
                    + "`numbers1` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers2` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers3` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers4` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers5` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers6` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers7` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers8` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers9` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers10` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers11` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers12` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers13` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers14` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers15` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers16` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers17` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers18` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers19` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers20` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers21` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers22` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers23` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers24` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers25` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers26` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers27` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers28` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers29` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers30` smallint(5) unsigned NOT NULL DEFAULT '0', "
                    + "`numbers32` smallint(5) unsigned NOT NULL DEFAULT '0' "
                    + ") ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci");
            
            stmt.executeUpdate("CREATE TABLE  `pim`.`contacts` ( "
                    + "`name` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '', "
                    + "`mail` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '', "
                    + "`number` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '', "
                    + "`description1` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '', "
                    + "`content1` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '', "
                    + "`description2` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '', "
                    + "`content2` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '', "
                    + "`description3` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '', "
                    + "`content3` varchar(255) COLLATE latin1_general_ci NOT NULL DEFAULT '' "
                    + ") ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci");
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonTest;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelServer;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldServer;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
