/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pim.event;

import java.awt.Color;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;

/**
 * Class EventSlot shows todos in panel
 * 
 * @author Joerg Federspiel
 */
public class EventItem extends javax.swing.JPanel {
    
    private static final SimpleDateFormat SDF_DATE = new SimpleDateFormat("dd.MM.yyyy");
    private static final SimpleDateFormat SDF_TIME = new SimpleDateFormat("HH:mm");
    private static final Color BACK_COLOR = new Color(178, 216, 255);
    private static final Color SELECT_COLOR = new Color(209,232,255);
    private static final Color TITLE_BACK_COLOR = new Color(0, 0, 153);
    private static final Color TITLE_SELECT_COLOR = new Color(56,56,201);

    private int position;
    private Event event;
    /**
     * Creates new form EventSlot
     */
    public EventItem(Event event) {
        initComponents();
        this.event = event;
        position = 0;
        update();
    }
    
    public void update() {
        jLabelTitle.setText(event.getTitle());
        jLabelDate.setText(SDF_DATE.format(event.getDate()));
        jLabelTime.setText(SDF_TIME.format(event.getDate()));
        jTextAreaContent.setText((event.getContent().isEmpty()) ? "Keine Beschreibung vorhanden." : event.getContent());
    }
    
    
    public Event getEvent() {
        return event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
        
    }
    
    public int getPosition() {
        return position;
    }
    
    public void setPosition(int position) {
        this.position = position;
    }
    
    
    public void addListener(MouseListener listener) {
        addMouseListener(listener);
        jTextAreaContent.addMouseListener(listener);
        jLabelDelete.addMouseListener(listener);
    }
    
    public void addCloseListener(MouseListener listener) {
        jLabelDelete.addMouseListener(listener);
    }
    
    public void select() {
        setBackground(SELECT_COLOR);
        jPanelTitle.setBackground(TITLE_SELECT_COLOR);
    }
    
    public void unselect() {
        setBackground(BACK_COLOR);
        jPanelTitle.setBackground(TITLE_BACK_COLOR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneContent = new javax.swing.JScrollPane();
        jTextAreaContent = new javax.swing.JTextArea();
        jLabelDateCaption = new javax.swing.JLabel();
        jLabelTimeCaption = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jPanelTitle = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelDelete = new javax.swing.JLabel();

        setBackground(new java.awt.Color(158, 201, 245));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(270, 155));
        setRequestFocusEnabled(false);

        jTextAreaContent.setEditable(false);
        jTextAreaContent.setLineWrap(true);
        jTextAreaContent.setRows(5);
        jTextAreaContent.setFocusable(false);
        jScrollPaneContent.setViewportView(jTextAreaContent);

        jLabelDateCaption.setText("Datum:");

        jLabelTimeCaption.setText("Uhrzeit:");

        jLabelDate.setText("10.10.2012");

        jLabelTime.setText("10:00");

        jPanelTitle.setBackground(new java.awt.Color(0, 0, 153));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Termin");
        jLabelTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 2, 0));

        jLabelDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDelete.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDelete.setText("x");
        jLabelDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 2, 5));
        jLabelDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelDelete))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelDelete)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelDateCaption)
                .addGap(6, 6, 6)
                .addComponent(jLabelDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTimeCaption)
                .addGap(6, 6, 6)
                .addComponent(jLabelTime)
                .addGap(10, 10, 10))
            .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneContent)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateCaption)
                    .addComponent(jLabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTimeCaption)
                    .addComponent(jLabelTime))
                .addGap(3, 3, 3)
                .addComponent(jScrollPaneContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDateCaption;
    private javax.swing.JLabel jLabelDelete;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelTimeCaption;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JScrollPane jScrollPaneContent;
    private javax.swing.JTextArea jTextAreaContent;
    // End of variables declaration//GEN-END:variables
}
